name: publish npm

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      # - name: authority npm
      #   run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: run install
        run: npm install
      - name: run release
        run: npm run release -- --tag=${{ github.ref }} --npm_token=${{ secrets.NPM_TOKEN }}
        # - name: Publish to NPMJS
        #   run: yarn && npm run release -- --tag=${{ github.ref }} --npm_token=${{ secrets.NPM_TOKEN }}
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
